"""Search provenance graph — tracks the full discovery path from query to source to URL to entity.

Node types
  seed_query  — initial research entity/query supplied by the user
  llm_query   — query generated by the LLM during post-ingestion reasoning
  source      — discovery source (gdelt, bbc_world, openalex, duckduckgo, …)
  url         — a specific document URL
  entity      — a named entity extracted from a document

Edge types
  queried        — (seed_query|llm_query) → source   — query was run against this source
  returned       — source → url                      — source yielded this URL
  triggered_by   — url → entity                      — entity was found in this document
  triggered      — entity → llm_query                — entity prompted a new LLM query
  generated      — url → llm_query                   — LLM reasoning on a doc created this query

Example path
  [seed_query: "Sudan Conflict"]
    --queried--> [source: gdelt]
                 --returned--> [url: https://gdelt.org/…]
                                --triggered_by--> [entity: "RSF"]
                                                   --triggered--> [llm_query: "RSF atrocities Sudan 2023"]
                                                                   --queried--> [source: duckduckgo]
                                                                                --returned--> [url: …]

The graph is persisted as JSON and can be exported as GEXF for Gephi / NetworkX.

Thread safety: all mutations go through a single lock; reads are lock-free (snapshot).
"""

from __future__ import annotations

import json
import threading
from collections import Counter
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Optional


def _now() -> str:
    return datetime.now(timezone.utc).isoformat()


def _xml_escape(s: str) -> str:
    return (
        s.replace("&", "&amp;")
        .replace('"', "&quot;")
        .replace("<", "&lt;")
        .replace(">", "&gt;")
    )


class SearchGraph:
    """Thread-safe, file-backed directed search provenance graph.

    Internal representation
    -----------------------
    _nodes  : dict[node_id, {id, type, label, first_seen, hits, …}]
    _edges  : list[{src, dst, type, timestamp, …}]
    _edge_set: set[(src_id, dst_id, edge_type)] — O(1) duplicate guard
    """

    def __init__(self, path: Path) -> None:
        self._path = path
        self._lock = threading.Lock()
        self._nodes: dict[str, dict] = {}
        self._edges: list[dict] = []
        self._edge_set: set[tuple[str, str, str]] = set()
        if path.exists():
            self._load()

    # ── Persistence ────────────────────────────────────────────────────────

    def _load(self) -> None:
        try:
            data = json.loads(self._path.read_text(encoding="utf-8"))
            self._nodes = {n["id"]: n for n in data.get("nodes", [])}
            self._edges = data.get("edges", [])
            self._edge_set = {
                (e["src"], e["dst"], e["type"]) for e in self._edges
            }
        except Exception:
            pass  # start fresh on corrupt file

    def save(self) -> None:
        with self._lock:
            self._path.parent.mkdir(parents=True, exist_ok=True)
            data = {
                "nodes": list(self._nodes.values()),
                "edges": self._edges,
                "stats": {
                    "nodes": len(self._nodes),
                    "edges": len(self._edges),
                    "saved_at": _now(),
                },
            }
            self._path.write_text(json.dumps(data, indent=2), encoding="utf-8")

    # ── Node / edge primitives ─────────────────────────────────────────────

    @staticmethod
    def _nid(node_type: str, label: str) -> str:
        return f"{node_type}::{label}"

    def add_node(self, node_type: str, label: str, **attrs: Any) -> str:
        nid = self._nid(node_type, label)
        with self._lock:
            if nid not in self._nodes:
                self._nodes[nid] = {
                    "id": nid,
                    "type": node_type,
                    "label": label,
                    "first_seen": _now(),
                    "hits": 1,
                    **attrs,
                }
            else:
                self._nodes[nid]["hits"] = self._nodes[nid].get("hits", 1) + 1
        return nid

    def add_edge(
        self,
        src_type: str,
        src_label: str,
        dst_type: str,
        dst_label: str,
        edge_type: str,
        **attrs: Any,
    ) -> None:
        src_id = self.add_node(src_type, src_label)
        dst_id = self.add_node(dst_type, dst_label)
        key = (src_id, dst_id, edge_type)
        with self._lock:
            if key not in self._edge_set:
                self._edges.append(
                    {"src": src_id, "dst": dst_id, "type": edge_type,
                     "timestamp": _now(), **attrs}
                )
                self._edge_set.add(key)

    # ── High-level recording helpers ───────────────────────────────────────

    def record_seed_query(self, query: str) -> None:
        self.add_node("seed_query", query)

    def record_source_query(
        self,
        query: str,
        source: str,
        query_type: str = "seed_query",
    ) -> None:
        """Record that a query was run against a discovery source."""
        self.add_edge(query_type, query, "source", source, "queried")

    def record_url_found(
        self,
        url: str,
        title: str,
        source: str,
        trigger_query: Optional[str] = None,
        query_type: str = "seed_query",
    ) -> None:
        """Record that a source (and optionally a triggering query) returned a URL."""
        self.add_node("url", url, title=title[:120], ingested=False)
        self.add_edge("source", source, "url", url, "returned")
        if trigger_query:
            self.add_edge(query_type, trigger_query, "url", url, "returned")

    def mark_url_ingested(self, url: str) -> None:
        nid = self._nid("url", url)
        with self._lock:
            if nid in self._nodes:
                self._nodes[nid]["ingested"] = True
                self._nodes[nid]["ingested_at"] = _now()

    def record_entity_discovered(self, entity: str, from_url: str) -> None:
        """Record that an entity was extracted from a document."""
        self.add_edge("url", from_url, "entity", entity, "triggered_by")

    def record_llm_query(
        self,
        query: str,
        triggered_by_entity: Optional[str] = None,
        generated_from_url: Optional[str] = None,
    ) -> None:
        """Record a query produced by the LLM during reasoning."""
        self.add_node("llm_query", query)
        if triggered_by_entity:
            self.add_edge(
                "entity", triggered_by_entity, "llm_query", query, "triggered"
            )
        if generated_from_url:
            self.add_edge("url", generated_from_url, "llm_query", query, "generated")

    # ── Analytics ─────────────────────────────────────────────────────────

    def stats(self) -> dict:
        node_types = Counter(n["type"] for n in self._nodes.values())
        edge_types = Counter(e["type"] for e in self._edges)
        return {
            "total_nodes": len(self._nodes),
            "total_edges": len(self._edges),
            "node_types": dict(node_types),
            "edge_types": dict(edge_types),
        }

    def top_nodes(self, node_type: str, n: int = 10) -> list[tuple[str, int]]:
        """Return top-n nodes of a given type by hit count."""
        candidates = [
            (nd["label"], nd.get("hits", 1))
            for nd in self._nodes.values()
            if nd["type"] == node_type
        ]
        return sorted(candidates, key=lambda x: x[1], reverse=True)[:n]

    def path_to_url(self, url: str) -> list[dict]:
        """Return the chain of edges that led to a given URL (BFS from seeds)."""
        target_id = self._nid("url", url)
        if target_id not in self._nodes:
            return []
        # Build adjacency list
        children: dict[str, list[dict]] = {}
        for e in self._edges:
            children.setdefault(e["src"], []).append(e)
        # BFS
        queue = [target_id]
        visited = {target_id}
        # Reverse: find parents (edges where dst == target)
        parents: dict[str, list[dict]] = {}
        for e in self._edges:
            parents.setdefault(e["dst"], []).append(e)
        # Trace back one level
        path = parents.get(target_id, [])
        return path

    # ── Export ─────────────────────────────────────────────────────────────

    def to_gexf(self) -> str:
        """Export as GEXF 1.3 XML (Gephi / yEd / NetworkX compatible)."""
        TYPE_COLOURS = {
            "seed_query": "#4A90D9",
            "llm_query":  "#7ED321",
            "source":     "#F5A623",
            "url":        "#9B9B9B",
            "entity":     "#D0021B",
        }
        lines = [
            '<?xml version="1.0" encoding="UTF-8"?>',
            '<gexf xmlns="http://gexf.net/1.3"'
            ' xmlns:viz="http://gexf.net/1.3/viz" version="1.3">',
            '  <graph defaultedgetype="directed">',
            '    <attributes class="node">',
            '      <attribute id="0" title="type" type="string"/>',
            '      <attribute id="1" title="hits" type="integer"/>',
            '      <attribute id="2" title="ingested" type="boolean"/>',
            '    </attributes>',
            '    <nodes>',
        ]
        for node in self._nodes.values():
            label = _xml_escape(node["label"][:80])
            nid   = _xml_escape(node["id"])
            colour = TYPE_COLOURS.get(node["type"], "#CCCCCC")
            r, g, b = int(colour[1:3], 16), int(colour[3:5], 16), int(colour[5:7], 16)
            lines.append(f'      <node id="{nid}" label="{label}">')
            lines.append(f'        <attvalues>')
            lines.append(f'          <attvalue for="0" value="{node["type"]}"/>')
            lines.append(f'          <attvalue for="1" value="{node.get("hits", 1)}"/>')
            lines.append(f'          <attvalue for="2" value="{str(node.get("ingested", False)).lower()}"/>')
            lines.append(f'        </attvalues>')
            lines.append(f'        <viz:color r="{r}" g="{g}" b="{b}"/>')
            lines.append(f'      </node>')
        lines.append("    </nodes>")
        lines.append("    <edges>")
        for i, edge in enumerate(self._edges):
            src = _xml_escape(edge["src"])
            dst = _xml_escape(edge["dst"])
            lbl = _xml_escape(edge["type"])
            lines.append(
                f'      <edge id="e{i}" source="{src}" target="{dst}" label="{lbl}"/>'
            )
        lines += ["    </edges>", "  </graph>", "</gexf>"]
        return "\n".join(lines)

    def to_networkx_dict(self) -> dict:
        """Return a NetworkX node-link JSON dict (compatible with nx.node_link_graph)."""
        return {
            "directed": True,
            "multigraph": False,
            "graph": {},
            "nodes": [
                {"id": n["id"], "label": n["label"], "type": n["type"],
                 "hits": n.get("hits", 1), "ingested": n.get("ingested", False)}
                for n in self._nodes.values()
            ],
            "links": [
                {"source": e["src"], "target": e["dst"],
                 "type": e["type"], "timestamp": e.get("timestamp", "")}
                for e in self._edges
            ],
        }


# ── Module-level active graph ──────────────────────────────────────────────────
# Set once per process when a project is loaded. Recording functions check
# `_active_graph is not None` before doing anything, so they're no-ops in
# legacy (no-project) mode.

_active_graph: Optional[SearchGraph] = None
_graph_lock = threading.Lock()


def set_active_graph(graph: Optional[SearchGraph]) -> None:
    global _active_graph
    with _graph_lock:
        _active_graph = graph


def get_active_graph() -> Optional[SearchGraph]:
    return _active_graph


# ── Convenience wrappers (safe to call even when no project is active) ──────────

def g_record_seed(query: str) -> None:
    g = get_active_graph()
    if g:
        g.record_seed_query(query)


def g_record_source_query(query: str, source: str, query_type: str = "seed_query") -> None:
    g = get_active_graph()
    if g:
        g.record_source_query(query, source, query_type)


def g_record_url(
    url: str,
    title: str,
    source: str,
    trigger_query: Optional[str] = None,
    query_type: str = "seed_query",
) -> None:
    g = get_active_graph()
    if g:
        g.record_url_found(url, title, source, trigger_query, query_type)


def g_mark_ingested(url: str) -> None:
    g = get_active_graph()
    if g:
        g.mark_url_ingested(url)


def g_record_entity(entity: str, from_url: str) -> None:
    g = get_active_graph()
    if g:
        g.record_entity_discovered(entity, from_url)


def g_record_llm_query(
    query: str,
    triggered_by_entity: Optional[str] = None,
    generated_from_url: Optional[str] = None,
) -> None:
    g = get_active_graph()
    if g:
        g.record_llm_query(query, triggered_by_entity, generated_from_url)


def g_save() -> None:
    g = get_active_graph()
    if g:
        try:
            g.save()
        except Exception:
            pass
